In [5]:
import numpy as np


In [6]:
mean=[0, 10, 5, 20, 15]
variance=[1,2,4,1.2,7]

# Collecting Training and Test samples 

In [53]:
sam=np.random.choice(5, 50000, p=[0.1,0.25,0.3,0.25,0.1])
test_sam=np.random.choice(5, 10000, p=[0.1,0.25,0.3,0.25,0.1])

In [54]:
estimated_priors=[0,0,0,0,0]
estimated_test_priors=[0,0,0,0,0]
training_samples=[]
samples_in_class=[0,0,0,0,0]
test_samples=[]
estimated_mean=[int(0),int(0),int(0),int(0),int(0)]
estimated_variances=[]
for i in range(50000):
    training_samples.append([np.random.normal(mean[sam[i]], np.sqrt(variance[sam[i]]),1),sam[i]])
for i in range(10000):
    test_samples.append([np.random.normal(mean[test_sam[i]], np.sqrt(variance[test_sam[i]]),1),test_sam[i]])
    estimated_test_priors[test_samples[i][1]]+=1
for i in range(50000):
    estimated_mean[sam[i]]=training_samples[i][0]+estimated_mean[sam[i]]
    estimated_priors[sam[i]]=1+estimated_priors[sam[i]]
for i in range(5):
    estimated_mean[i]=estimated_mean[i]/estimated_priors[i]

In [55]:
estimated_test_priors

[986, 2441, 3024, 2575, 974]

In [56]:
estimated_mean

[array([-0.01055777]),
 array([9.99695473]),
 array([5.00883738]),
 array([20.00020883]),
 array([15.02604959])]

In [57]:
estimated_priors

[4971, 12306, 14972, 12660, 5091]

In [58]:
variance=[0,0,0,0,0]
t1=[]
for i in range(50000):
    t1.append(training_samples[i][0]-mean[training_samples[i][1]])
t2=np.square(t1)

In [59]:
for i in range(50000):
    variance[training_samples[i][1]]=variance[training_samples[i][1]]+t2[i]

In [60]:
for i in range(5):
    variance[i]=variance[i]/estimated_priors[i]

In [61]:
variance

[array([0.93642047]),
 array([1.97134901]),
 array([4.12252236]),
 array([1.18714508]),
 array([7.08909008])]

# Equal Priors and Equal Variances

In [62]:
#computing equal variance
s=0
temp=[]
for i in range(50000):
    s=s+training_samples[i][0]
    temp.append(training_samples[i][0])
equal_mean=s/50000


In [63]:
temp=temp-equal_mean
print(temp)

[[ 8.30737128]
 [ 8.78427907]
 [-5.57950928]
 ...
 [ 1.26475168]
 [-5.09929607]
 [-7.35747064]]


In [64]:
temp=np.square(temp)
temp=sum(temp)
equal_variance=temp/49999

In [65]:
equal_variance

array([47.8456121])

In [66]:
test_prior=[0,0,0,0,0]
for i in range(10000):
    test_prior[test_samples[i][1]]=test_prior[test_samples[i][1]]+1
print(test_prior)

[986, 2441, 3024, 2575, 974]


In [67]:
results=[]
for i in range(50000):
    m=-np.square(training_samples[i][0]- estimated_mean[0])
    c=0
    for k in range(1,5):
        if(m<(-np.square(training_samples[i][0]- estimated_mean[k]))):
            m=-np.square(training_samples[i][0]- estimated_mean[k])
            c=k;
    results.append([training_samples[i][0],c])

In [68]:
accuracy=[[0,0],[0,0],[0,0],[0,0],[0,0]]

In [69]:
for i in range(10000):
    if(results[i][1]==test_samples[i][1]):
        accuracy[test_samples[i][1]][0]=accuracy[test_samples[i][1]][0]+1
    else:
        accuracy[test_samples[i][1]][1]=accuracy[test_samples[i][1]][1]+1
   

In [70]:
accuracy

[[127, 859], [672, 1769], [720, 2304], [676, 1899], [89, 885]]

In [71]:
accuracy_in_percent=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(5):
    accuracy_in_percent[i][0]=(accuracy[i][0]/test_prior[i])*100
    accuracy_in_percent[i][1]=(accuracy[i][1]/test_prior[i])*100
    

In [72]:
accuracy_in_percent

[[12.880324543610547, 87.11967545638946],
 [27.52970094223679, 72.47029905776321],
 [23.809523809523807, 76.19047619047619],
 [26.252427184466022, 73.74757281553399],
 [9.137577002053387, 90.86242299794661]]

# Estimated Priors and equal Variances 

In [73]:
def discriminant(x,mean,variance,prior):
    s=-np.square(x-mean)/(2*variance)+np.log(prior)
    return s

In [74]:
results=[]
for i in range(10000):
    m=discriminant(test_samples[i][0], estimated_mean[0], equal_variance, test_prior[0]/10000)
    c=0
    for k in range(1,5):
        if(m<(discriminant(test_samples[i][0], estimated_mean[k], equal_variance, test_prior[k]/10000))):
            m=discriminant(test_samples[i][0], estimated_mean[k], equal_variance, test_prior[k]/10000)
            c=k;
    results.append([test_samples[i][0],c])

In [75]:
results

[[array([19.21793398]), 3],
 [array([15.13718881]), 3],
 [array([5.69732629]), 2],
 [array([21.08265041]), 3],
 [array([7.12435999]), 2],
 [array([1.46610449]), 2],
 [array([0.56164025]), 2],
 [array([14.03433048]), 1],
 [array([7.5219122]), 2],
 [array([0.07717866]), 2],
 [array([11.01184464]), 1],
 [array([19.54995875]), 3],
 [array([12.1412786]), 1],
 [array([6.83518647]), 2],
 [array([8.40621418]), 2],
 [array([9.0213602]), 2],
 [array([19.68452634]), 3],
 [array([9.71477807]), 1],
 [array([4.47022372]), 2],
 [array([9.53697828]), 2],
 [array([4.35720486]), 2],
 [array([20.27918982]), 3],
 [array([0.01192675]), 2],
 [array([-0.3373173]), 2],
 [array([17.68932856]), 3],
 [array([19.80463854]), 3],
 [array([0.64785039]), 2],
 [array([3.14802171]), 2],
 [array([1.29101919]), 2],
 [array([19.81634372]), 3],
 [array([3.54525361]), 2],
 [array([18.78463179]), 3],
 [array([1.09547068]), 2],
 [array([1.56543831]), 2],
 [array([11.39529833]), 1],
 [array([9.95848127]), 1],
 [array([10.80886

In [76]:
accuracy=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(10000):
    if(results[i][1]==test_samples[i][1]):
        accuracy[test_samples[i][1]][0]=accuracy[test_samples[i][1]][0]+1
    else:
        accuracy[test_samples[i][1]][1]=accuracy[test_samples[i][1]][1]+1
 

In [77]:
accuracy

[[0, 986], [1535, 906], [2984, 40], [2575, 0], [0, 974]]

In [78]:
accuracy_in_percent=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(5):
    accuracy_in_percent[i][0]=(accuracy[i][0]/estimated_test_priors[i])*100
    accuracy_in_percent[i][1]=(accuracy[i][1]/estimated_test_priors[i])*100
    

In [79]:
accuracy_in_percent

[[0.0, 100.0],
 [62.88406390823433, 37.115936091765676],
 [98.67724867724867, 1.3227513227513228],
 [100.0, 0.0],
 [0.0, 100.0]]

# Equal Priors and Estimated Variance

In [80]:
def discriminant2(x,mean,variance):
    s=-np.square(x-mean)/(2*variance)-np.log(variance)
    return s

In [81]:
results=[]
for i in range(10000):
    m=discriminant2(test_samples[i][0], estimated_mean[0], equal_variance)
    c=0
    for k in range(1,5):
        if(m<(discriminant2(test_samples[i][0], estimated_mean[k], equal_variance))):
            m=discriminant2(test_samples[i][0], estimated_mean[k], equal_variance)
            c=k;
    results.append([test_samples[i][0],c])

In [82]:
accuracy=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(10000):
    if(results[i][1]==test_samples[i][1]):
        accuracy[test_samples[i][1]][0]=accuracy[test_samples[i][1]][0]+1
    else:
        accuracy[test_samples[i][1]][1]=accuracy[test_samples[i][1]][1]+1
 

In [83]:
accuracy

[[977, 9], [2254, 187], [2375, 649], [2550, 25], [629, 345]]

In [84]:
accuracy_in_percent=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(5):
    accuracy_in_percent[i][0]=(accuracy[i][0]/test_prior[i])*100
    accuracy_in_percent[i][1]=(accuracy[i][1]/test_prior[i])*100
    

In [85]:
accuracy_in_percent

[[99.08722109533468, 0.9127789046653144],
 [92.33920524375256, 7.66079475624744],
 [78.53835978835978, 21.461640211640212],
 [99.02912621359224, 0.9708737864077669],
 [64.57905544147845, 35.42094455852156]]

# Estimated Priors and Estimated Variance

In [86]:
def discriminant3(x,mean,variance, prior):
    s=-np.square(x-mean)/(2*variance)-np.log(variance)+np.log(prior)
    return s

In [87]:
results=[]
for i in range(10000):
    m=discriminant3(test_samples[i][0], estimated_mean[0], equal_variance, estimated_priors[0]/10000)
    c=0
    for k in range(1,5):
        if(m<(discriminant3(test_samples[i][0], estimated_mean[k], equal_variance, estimated_priors[k]/10000))):
            m=discriminant3(test_samples[i][0], estimated_mean[k], equal_variance, estimated_priors[k]/10000)
            c=k;
    results.append([test_samples[i][0],c])

In [88]:
accuracy=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(10000):
    if(results[i][1]==test_samples[i][1]):
        accuracy[test_samples[i][1]][0]=accuracy[test_samples[i][1]][0]+1
    else:
        accuracy[test_samples[i][1]][1]=accuracy[test_samples[i][1]][1]+1
 

In [89]:
accuracy

[[0, 986], [1649, 792], [2975, 49], [2575, 0], [0, 974]]

In [90]:
accuracy_in_percent=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(5):
    accuracy_in_percent[i][0]=(accuracy[i][0]/test_prior[i])*100
    accuracy_in_percent[i][1]=(accuracy[i][1]/test_prior[i])*100
    

In [91]:
accuracy_in_percent

[[0.0, 100.0],
 [67.55428103236379, 32.44571896763622],
 [98.37962962962963, 1.6203703703703702],
 [100.0, 0.0],
 [0.0, 100.0]]