In [1]:
import numpy as np


In [2]:
mean=[0, 10, 5, 20, 15]
variance=[1,2,4,1.2,7]

# Collecting Training and Test samples 

In [3]:
sam=np.random.choice(5, 50000, p=[0.2,0.2,0.2,0.2,0.2])
test_sam=np.random.choice(5, 10000, p=[0.2,0.2,0.2,0.2,0.2])

In [4]:
estimated_priors=[0,0,0,0,0]
estimated_test_priors=[0,0,0,0,0]
training_samples=[]
samples_in_class=[0,0,0,0,0]
test_samples=[]
estimated_mean=[int(0),int(0),int(0),int(0),int(0)]
estimated_variances=[]
for i in range(50000):
    training_samples.append([np.random.normal(mean[sam[i]], np.sqrt(variance[sam[i]]),1),sam[i]])
for i in range(10000):
    test_samples.append([np.random.normal(mean[test_sam[i]], np.sqrt(variance[test_sam[i]]),1),test_sam[i]])
    estimated_test_priors[test_samples[i][1]]+=1
for i in range(50000):
    estimated_mean[sam[i]]=training_samples[i][0]+estimated_mean[sam[i]]
    estimated_priors[sam[i]]=1+estimated_priors[sam[i]]
for i in range(5):
    estimated_mean[i]=estimated_mean[i]/estimated_priors[i]

In [5]:
estimated_test_priors

[1958, 2028, 2029, 1959, 2026]

In [6]:
estimated_mean

[array([-0.02552495]),
 array([9.98408893]),
 array([4.98096291]),
 array([20.02829303]),
 array([14.99797972])]

In [7]:
estimated_priors

[9977, 9902, 10041, 10049, 10031]

In [8]:
variance=[0,0,0,0,0]
t1=[]
for i in range(50000):
    t1.append(training_samples[i][0]-mean[training_samples[i][1]])
t2=np.square(t1)

In [9]:
for i in range(50000):
    variance[training_samples[i][1]]=variance[training_samples[i][1]]+t2[i]

In [10]:
for i in range(5):
    variance[i]=variance[i]/estimated_priors[i]

In [11]:
variance

[array([0.98626808]),
 array([2.02956113]),
 array([3.99841868]),
 array([1.19494407]),
 array([6.91318921])]

# Equal Priors and Equal Variances

In [12]:
#computing equal variance
s=0
temp=[]
for i in range(50000):
    s=s+training_samples[i][0]
    temp.append(training_samples[i][0])
equal_mean=s/50000


In [13]:
temp=temp-equal_mean
print(temp)

[[-10.75159855]
 [  1.27593205]
 [ -6.34818837]
 ...
 [ -0.49524905]
 [  3.31729503]
 [ -6.42960069]]


In [14]:
temp=np.square(temp)
temp=sum(temp)
equal_variance=temp/49999

In [15]:
equal_variance

array([53.36757298])

In [29]:
test_prior=[0,0,0,0,0]
for i in range(10000):
    test_prior[test_samples[i][1]]=test_prior[test_samples[i][1]]+1
print(test_prior)

[1958, 2028, 2029, 1959, 2026]


In [38]:
results=[]
for i in range(50000):
    m=-np.square(training_samples[i][0]- estimated_mean[0])
    c=0
    for j in range(1,5):
        if(m<(-np.square(training_samples[i][0]- estimated_mean[j]))):
            m=-np.square(training_samples[i][0]- estimated_mean[j])
            c=j;
    results.append([training_samples[i][0],c])

In [39]:
accuracy=[[0,0],[0,0],[0,0],[0,0],[0,0]]

In [40]:
for i in range(10000):
    if(results[i][1]==test_samples[i][1]):
        accuracy[test_samples[i][1]][0]=accuracy[test_samples[i][1]][0]+1
    else:
        accuracy[test_samples[i][1]][1]=accuracy[test_samples[i][1]][1]+1
   

In [41]:
accuracy

[[428, 1530], [484, 1544], [335, 1694], [484, 1475], [284, 1742]]

In [42]:
accuracy_in_percent=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(5):
    accuracy_in_percent[i][0]=(accuracy[i][0]/estimated_test_priors[i])*100
    accuracy_in_percent[i][1]=(accuracy[i][1]/estimated_test_priors[i])*100
    

In [43]:
accuracy_in_percent

[[21.859039836567927, 78.14096016343207],
 [23.86587771203156, 76.13412228796844],
 [16.510596352883194, 83.48940364711682],
 [24.70648289943849, 75.29351710056152],
 [14.0177690029615, 85.9822309970385]]

# Estimated Priors and equal Variances 

In [44]:
def discriminant(x,mean,variance,prior):
    s=-np.square(x-mean)/(2*variance)+np.log(prior)
    return s

In [45]:
results=[]
for i in range(10000):
    m=discriminant(test_samples[i][0], estimated_mean[0], equal_variance, estimated_test_priors[0]/10000)
    c=0
    for k in range(1,5):
        if(m<(discriminant(test_samples[i][0], estimated_mean[k], equal_variance, estimated_test_priors[k]/10000))):
            m=discriminant(test_samples[i][0], estimated_mean[k], equal_variance, estimated_test_priors[k]/10000)
            c=k;
    results.append([test_samples[i][0],c])

In [46]:
results

[[array([21.32716338]), 3],
 [array([1.99580104]), 0],
 [array([-0.38743766]), 0],
 [array([1.64449411]), 0],
 [array([-0.01252189]), 0],
 [array([3.8609996]), 2],
 [array([5.5092509]), 2],
 [array([10.60902752]), 1],
 [array([20.73952522]), 3],
 [array([2.644878]), 2],
 [array([15.25021335]), 4],
 [array([18.45566916]), 3],
 [array([0.50923948]), 0],
 [array([1.60562567]), 0],
 [array([18.73130867]), 3],
 [array([3.10528813]), 2],
 [array([18.05150008]), 3],
 [array([19.37364061]), 3],
 [array([19.14149174]), 3],
 [array([18.69500154]), 3],
 [array([16.89358123]), 4],
 [array([-0.13030742]), 0],
 [array([9.74650054]), 1],
 [array([9.95892948]), 1],
 [array([-0.10237136]), 0],
 [array([20.71350257]), 3],
 [array([11.58929398]), 1],
 [array([0.44610657]), 0],
 [array([11.15703628]), 1],
 [array([13.53917834]), 4],
 [array([8.74037456]), 1],
 [array([21.22870981]), 3],
 [array([13.0332778]), 4],
 [array([1.3257844]), 0],
 [array([12.47805824]), 1],
 [array([-0.57810154]), 0],
 [array([2.

In [47]:
accuracy=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(10000):
    if(results[i][1]==test_samples[i][1]):
        accuracy[test_samples[i][1]][0]=accuracy[test_samples[i][1]][0]+1
    else:
        accuracy[test_samples[i][1]][1]=accuracy[test_samples[i][1]][1]+1
 

In [48]:
accuracy

[[1925, 33], [1869, 159], [1664, 365], [1908, 51], [1394, 632]]

In [49]:
accuracy_in_percent=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(5):
    accuracy_in_percent[i][0]=(accuracy[i][0]/estimated_test_priors[i])*100
    accuracy_in_percent[i][1]=(accuracy[i][1]/estimated_test_priors[i])*100
    

In [50]:
accuracy_in_percent

[[98.31460674157303, 1.6853932584269662],
 [92.15976331360946, 7.840236686390532],
 [82.01084277969443, 17.989157220305568],
 [97.39663093415007, 2.6033690658499236],
 [68.80552813425469, 31.19447186574531]]

# Equal Priors and Estimated Variance

In [51]:
def discriminant2(x,mean,variance):
    s=-np.square(x-mean)/(2*variance)-np.log(variance)
    return s

In [54]:
results=[]
for i in range(10000):
    m=discriminant2(test_samples[i][0], estimated_mean[0], equal_variance)
    c=0
    for k in range(1,5):
        if(m<(discriminant2(test_samples[i][0], estimated_mean[k], equal_variance))):
            m=discriminant2(test_samples[i][0], estimated_mean[k], equal_variance)
            c=k;
    results.append([test_samples[i][0],c])

In [55]:
accuracy=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(10000):
    if(results[i][1]==test_samples[i][1]):
        accuracy[test_samples[i][1]][0]=accuracy[test_samples[i][1]][0]+1
    else:
        accuracy[test_samples[i][1]][1]=accuracy[test_samples[i][1]][1]+1
 

In [56]:
accuracy

[[1945, 13], [1869, 159], [1602, 427], [1936, 23], [1332, 694]]

In [57]:
accuracy_in_percent=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(5):
    accuracy_in_percent[i][0]=(accuracy[i][0]/estimated_test_priors[i])*100
    accuracy_in_percent[i][1]=(accuracy[i][1]/estimated_test_priors[i])*100
    

In [59]:
accuracy_in_percent

[[99.33605720122574, 0.6639427987742594],
 [92.15976331360946, 7.840236686390532],
 [78.95515032035485, 21.044849679645143],
 [98.82593159775396, 1.174068402246044],
 [65.74531095755182, 34.25468904244817]]

# Estimated Priors and Estimated Variance

In [60]:
def discriminant3(x,mean,variance, prior):
    s=-np.square(x-mean)/(2*variance)-np.log(variance)+np.log(prior)
    return s

In [61]:
results=[]
for i in range(10000):
    m=discriminant3(test_samples[i][0], estimated_mean[0], equal_variance, estimated_priors[0]/10000)
    c=0
    for k in range(1,5):
        if(m<(discriminant3(test_samples[i][0], estimated_mean[k], equal_variance, estimated_priors[k]/10000))):
            m=discriminant3(test_samples[i][0], estimated_mean[k], equal_variance, estimated_priors[k]/10000)
            c=k;
    results.append([test_samples[i][0],c])

In [62]:
accuracy=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(10000):
    if(results[i][1]==test_samples[i][1]):
        accuracy[test_samples[i][1]][0]=accuracy[test_samples[i][1]][0]+1
    else:
        accuracy[test_samples[i][1]][1]=accuracy[test_samples[i][1]][1]+1
 

In [63]:
accuracy

[[1943, 15], [1833, 195], [1639, 390], [1936, 23], [1351, 675]]

In [64]:
accuracy_in_percent=[[0,0],[0,0],[0,0],[0,0],[0,0]]
for i in range(5):
    accuracy_in_percent[i][0]=(accuracy[i][0]/estimated_test_priors[i])*100
    accuracy_in_percent[i][1]=(accuracy[i][1]/estimated_test_priors[i])*100
    

In [65]:
accuracy_in_percent

[[99.23391215526047, 0.7660878447395302],
 [90.38461538461539, 9.615384615384617],
 [80.77870872350911, 19.22129127649088],
 [98.82593159775396, 1.174068402246044],
 [66.68311944718658, 33.31688055281343]]