In [3]:
#Sai Ram
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()


In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris["target_names"])

['setosa' 'versicolor' 'virginica']


In [6]:
data=iris["data"]
data.shape

(150, 4)

In [7]:
target=iris["target"]

In [8]:
target.shape

(150,)

In [89]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [53]:
data_samples=[[],[],[]]
for i in range(len(target)):
    data_samples[target[i]].append([data[i]])

In [54]:
for i in range(3):
    data_samples[i]=np.reshape(np.array(data_samples[i]),[50,4])
    print(np.array(data_samples[i]).shape)

(50, 4)
(50, 4)
(50, 4)


In [55]:
data_samples=np.array(data_samples)

In [56]:
data_samples.shape

(3, 50, 4)

In [57]:
train_data_samples=[]
test_data_samples=[]
train_target_samples=[]
test_target_samples=[]
for i in range(3):
    train_data_samples.append(data_samples[i][:35])
    test_target_samples.append(target)
train_data_samples=np.array(train_data_samples)

for i in range(3):
    test_data_samples.append(data_samples[i][35:50])
test_data_samples=np.array(test_data_samples)

In [58]:
test_data_samples.shape


(3, 15, 4)

In [59]:
mean=np.mean(train_data_samples,axis=1)

In [75]:
mean.shape

(3, 4)

In [61]:
def variance(x):
    m=np.average(x)
    dev=x-m
    sqr=dev**2
    return np.sum(sqr)/len(x)
def corrcoeff(x, y):
    m1=np.average(x)
    m2=np.average(y)
    dev1=x-m1
    dev2=y-m2
    dev=dev1*dev2
    corr=np.sum(dev)/len(x)
    #den=np.sqrt(variance(x))*np.sqrt(variance(y))
    return corr
def cov(x, y):
    return corrcoeff(x, y);
def covariance_matrix(x):
    cov=[[None, None, None, None],[None, None, None, None],[None, None, None, None],[None, None, None, None]]
    for i in range(4):
        for j in range(4):
            if(i==j):
                cov[i][j]=variance(x[i])
            else:
                cov[i][j]=corrcoeff(x[i],x[j])
    return cov

In [62]:
train_data_samples

array([[[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [63]:
cov_prereq=[[],[],[]]

In [64]:
for j in range(3):
    for k in range(4):
        l=[]
        for i in range(35):
            l.append(train_data_samples[j][i][k])
        cov_prereq[j].append(l)
        l=[]

In [65]:
cov_prereq=np.array(cov_prereq)

In [66]:
cov_prereq.shape


(3, 4, 35)

In [67]:
cov_mat=[]
for i in range(3):
    cov_mat.append(np.array(covariance_matrix(cov_prereq[i][:])))


In [68]:
train_data_samples.shape

(3, 35, 4)

In [69]:
cov_mat


[array([[ 0.12762449,  0.09972245,  0.01333061,  0.01404082],
        [ 0.09972245,  0.13644082, -0.0012898 ,  0.01306122],
        [ 0.01333061, -0.0012898 ,  0.02919184,  0.00469388],
        [ 0.01404082,  0.01306122,  0.00469388,  0.00987755]]),
 array([[0.27678367, 0.09284082, 0.17644898, 0.0544898 ],
        [0.09284082, 0.09929796, 0.08330612, 0.04391837],
        [0.17644898, 0.08330612, 0.21722449, 0.07853061],
        [0.0544898 , 0.04391837, 0.07853061, 0.04530612]]),
 array([[0.47056327, 0.12622041, 0.37013061, 0.04582041],
        [0.12622041, 0.11890612, 0.09247347, 0.04627755],
        [0.37013061, 0.09247347, 0.35733878, 0.05773061],
        [0.04582041, 0.04627755, 0.05773061, 0.07262041]])]

In [70]:
dets=[]
for i in range(3):
    dets.append(np.linalg.det(cov_mat[i]))

In [71]:
dets

[1.4709203081573145e-06, 2.2508251548711838e-05, 0.00011957160190016035]

In [83]:
mat_inv=[]
for i in range(3):
    mat_inv.append(np.linalg.inv(cov_mat[i]))

# Assuming Distinct Covariance Matrix 

In [118]:
#Since train data set has equal number of instances of each class priors are equal and hence avoided
def descriminant1(dets, sample, mean, invs):
    x=np.reshape(sample, [1,4])
    ans= -np.log(dets)/2-(np.dot(np.dot(x, invs), np.transpose(x))-2*np.dot(np.dot(x, invs),mean)+np.dot(np.dot(np.transpose(mean), invs),mean))/2
    return ans         

In [119]:
train_data_samples.shape

(3, 35, 4)

# Testing model over Training Data

In [120]:
pred=[]
maximum=-1

for i in range(3):
    for k in range(35):
        c=0
        maximum=descriminant1(dets[0], train_data_samples[i][k], mean[0], mat_inv[0])
        for j in range(1,3):
            if(descriminant1(dets[j], train_data_samples[i][k], mean[j], mat_inv[j])>maximum):
                maximum=descriminant1(dets[j], train_data_samples[i][k], mean[j], mat_inv[j])
                c=j
        pred.append(c)


In [121]:
accuracy=[0,0,0]
for i in range(3):
    for j in range(35):
        if(pred[j+35*i]==i):
            accuracy[i]+=1

In [122]:
accuracy

[35, 33, 34]

# Testing model over Test Data 

In [123]:
pred=[]
maximum=-1

for i in range(3):
    for k in range(15):
        c=0
        maximum=descriminant1(dets[0], test_data_samples[i][k], mean[0], mat_inv[0])
        for j in range(1,3):
            if(descriminant1(dets[j], test_data_samples[i][k], mean[j], mat_inv[j])>maximum):
                maximum=descriminant1(dets[j], test_data_samples[i][k], mean[j], mat_inv[j])
                c=j
        pred.append(c)


In [124]:
accuracy=[0,0,0]
for i in range(3):
    for j in range(15):
        if(pred[j+15*i]==i):
            accuracy[i]+=1

In [125]:
accuracy

[15, 15, 15]

# Using Same Covariance Matrix 

In [126]:
#Since all classes have equal instances of training examples it suffices to take mean of the inverse of covariance matrix as common covariance matrix
common_cov_inv=sum(mat_inv)/3

In [127]:
#Since train data set has equal number of instances of each class priors are equal and hence avoided
def descriminant2(sample, mean, invs):
    x=np.reshape(sample, [1,4])
    ans= -(np.dot(np.dot(x, invs), np.transpose(x))-2*np.dot(np.dot(x, invs),mean)+np.dot(np.dot(np.transpose(mean), invs),mean))/2
    return ans       

## Testing the model over Train data 

In [133]:
pred=[]
maximum=-1

for i in range(3):
    for k in range(35):
        c=0
        maximum=descriminant1(dets[0], train_data_samples[i][k], mean[0], mat_inv[0])
        for j in range(1,3):
            if(descriminant1(dets[j], train_data_samples[i][k], mean[j], mat_inv[j])>maximum):
                maximum=descriminant1(dets[j], train_data_samples[i][k], mean[j], mat_inv[j])
                c=j
        pred.append(c)


In [134]:
accuracy=[0,0,0]
for i in range(3):
    for j in range(35):
        if(pred[j+35*i]==i):
            accuracy[i]+=1

In [135]:
accuracy

[35, 33, 34]

## Testing the model over Test Data 

In [136]:
pred=[]
maximum=-1
for i in range(3):
    for k in range(15):
        c=0
        maximum=descriminant2(test_data_samples[i][k], mean[0], common_cov_inv)
        for j in range(1,3):
            if(descriminant2( test_data_samples[i][k], mean[j], common_cov_inv)>maximum):
                maximum=descriminant2(test_data_samples[i][k], mean[j], common_cov_inv)
                c=j
        pred.append(c)

        

In [137]:
accuracy=[0,0,0]
for i in range(3):
    for j in range(15):
        if(pred[j+15*i]==i):
            accuracy[i]+=1

In [138]:
accuracy

[15, 15, 15]

# Using Same Covariance Matrix with off Diagonal Zero 

In [147]:
cov_off=common_cov_inv.copy()

In [148]:
for i in range(4):
    for j in range(4):
        if(i!=j):
            cov_off[i][j]=0

In [149]:
cov_off

array([[15.12836339,  0.        ,  0.        ,  0.        ],
       [ 0.        , 18.68492836,  0.        ,  0.        ],
       [ 0.        ,  0.        , 27.03157557,  0.        ],
       [ 0.        ,  0.        ,  0.        , 77.28965785]])

In [145]:
#Since train data set has equal number of instances of each class priors are equal and hence avoided
def descriminant3(sample, mean, invs):
    x=np.reshape(sample, [1,4])
    ans= -(np.dot(np.dot(x, invs), np.transpose(x))-2*np.dot(np.dot(x, invs),mean)+np.dot(np.dot(np.transpose(mean), invs),mean))/2
    return ans       

## Testing the model over Train data 

In [151]:
pred=[]
maximum=-1

for i in range(3):
    for k in range(35):
        c=0
        maximum=descriminant3( train_data_samples[i][k], mean[0], cov_off)
        for j in range(1,3):
            if(descriminant3( train_data_samples[i][k], mean[j], cov_off)>maximum):
                maximum=descriminant3( train_data_samples[i][k], mean[j], cov_off)
                c=j
        pred.append(c)


In [152]:
accuracy=[0,0,0]
for i in range(3):
    for j in range(35):
        if(pred[j+35*i]==i):
            accuracy[i]+=1

In [153]:
accuracy

[35, 34, 31]

## Testing the model over Test Data 

In [154]:
pred=[]
maximum=-1
for i in range(3):
    for k in range(15):
        c=0
        maximum=descriminant3(test_data_samples[i][k], mean[0], cov_off)
        for j in range(1,3):
            if(descriminant3( test_data_samples[i][k], mean[j], cov_off)>maximum):
                maximum=descriminant3(test_data_samples[i][k], mean[j], cov_off)
                c=j
        pred.append(c)

        

In [155]:
accuracy=[0,0,0]
for i in range(3):
    for j in range(15):
        if(pred[j+15*i]==i):
            accuracy[i]+=1

In [156]:
accuracy

[15, 15, 14]